name: pondsdataupdate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Project
      run: mvn clean package

    - name: Install Playwright Browsers
      run: mvn exec:java -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

    - name: Run Bgardhdiv
      run: mvn exec:java -Dexec.mainClass="src/main/java/pondsdataupdateBgardhdiv" -e
